name: Python application

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - uses: dschep/install-pipenv-action@v1
    - name: Install dependencies
      run: pipenv install --dev
    - name: pytest
      run: BUNDLE_DIR=`pwd`/BUNDLE_DIR pipenv run coverage run --source=. -m pytest
    - name: coverage report
      run: pipenv run coverage xml
    - uses: codecov/codecov-action@v1
      with:
        # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        file: ./coverage.xml # optional
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        post_status: true
    - name: lintly-flake8
      uses: grantmcconnaughey/lintly-flake8-github-action@v1.0
      with:
        # The GitHub API token to create reviews with
        token: ${{ secrets.GITHUB_TOKEN }}
        # Fail if "new" violations detected or "any", default "new"
        failIf: new
        # Additional arguments to pass to flake8, default "." (current directory)
        args: "--ignore=E121,E123 ."
